/* ═══════════════════════════════════════════════════════════
   menu-data.js – Menù della mensa (a cura di Sagre Prelibate)

   AUTO-GENERATED by tools/build-menu.py from menu.xlsx /
   menu_english.xlsx. Do NOT edit by hand: update the Excel
   files and re-run the script instead.

   Each day: { date, lunch[], dinner[] }. Each meal option is
   { it: [lines], en: [lines] } where the lines are the courses
   (first course / main / side). Option index 2 is vegetarian.
   ═══════════════════════════════════════════════════════════ */

const MENSA_MENU = [
  {
    "date": "2026-07-16",
    "lunch": [],
    "dinner": [
      {
        "it": [
          "Lasagna alla bolognese",
          "Roast beef",
          "Insalata mista"
        ],
        "en": [
          "Lasagna Bolognese",
          "Roast beef",
          "Mixed salad"
        ]
      },
      {
        "it": [
          "Riso con verdure",
          "pesce al forno",
          "Fagiolini"
        ],
        "en": [
          "Rice with vegetables",
          "Baked fish",
          "Green beans"
        ]
      },
      {
        "it": [
          "Lasagna alle verdure",
          "stracchino",
          "insalata mista"
        ],
        "en": [
          "Vegetable lasagna",
          "Stracchino cheese",
          "Mixed salad"
        ]
      }
    ]
  },
  {
    "date": "2026-07-17",
    "lunch": [
      {
        "it": [
          "Pasta al pesto",
          "Tacchino arrosto",
          "Piselli"
        ],
        "en": [
          "Pasta with pesto",
          "Roast turkey",
          "Peas"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "platessa al limone",
          "verdure al forno"
        ],
        "en": [
          "Basmati rice",
          "Plaice with lemon",
          "Baked vegetables"
        ]
      },
      {
        "it": [
          "Pasta alla norma",
          "Burger vegetale",
          "Piselli"
        ],
        "en": [
          "Pasta alla Norma",
          "Veggie burger",
          "Peas"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Gnocchi al pomodoro",
          "Orata al forno",
          "Verdure grigliate"
        ],
        "en": [
          "Gnocchi with tomato sauce",
          "Baked sea bream",
          "Grilled vegetables"
        ]
      },
      {
        "it": [
          "Pasta integrale alle verdure",
          "Hamburger di manzo",
          "Patate al forno"
        ],
        "en": [
          "Wholewheat pasta with vegetables",
          "Beef burger",
          "Baked potatoes"
        ]
      },
      {
        "it": [
          "Gnocchi al pomodoro",
          "hamburger vegetale",
          "Verdure grigliate"
        ],
        "en": [
          "Gnocchi with tomato sauce",
          "Veggie burger",
          "Grilled vegetables"
        ]
      }
    ]
  },
  {
    "date": "2026-07-18",
    "lunch": [
      {
        "it": [
          "Pasta tonno e pomodoro",
          "Lonza al forno",
          "Fagiolini"
        ],
        "en": [
          "Pasta with tuna and tomato",
          "Baked pork loin",
          "Green beans"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "branzino al forno",
          "Carote"
        ],
        "en": [
          "Basmati rice",
          "Baked sea bass",
          "Carrots"
        ]
      },
      {
        "it": [
          "pasta alla crudaiola",
          "Polpette di ceci",
          "Carote"
        ],
        "en": [
          "Pasta with raw tomato sauce",
          "Chickpea patties",
          "Carrots"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "pasta gratinata",
          "Prosciutto cotto",
          "Insalata"
        ],
        "en": [
          "Baked pasta (au gratin)",
          "Cooked ham",
          "Salad"
        ]
      },
      {
        "it": [
          "cannelloni ricotta e spinaci",
          "Platessa al forno",
          "Broccoli"
        ],
        "en": [
          "Ricotta and spinach cannelloni",
          "Baked plaice",
          "Broccoli"
        ]
      },
      {
        "it": [
          "Cannelloni ricotta e spinaci",
          "Insalata ricca( insalata, pom, ceci e feta)"
        ],
        "en": [
          "Ricotta and spinach cannelloni",
          "Rich salad (lettuce, tomato, chickpeas and feta)"
        ]
      }
    ]
  },
  {
    "date": "2026-07-19",
    "lunch": [
      {
        "it": [
          "Pasta primavera",
          "Pollo alla griglia",
          "fagiolini"
        ],
        "en": [
          "Pasta primavera",
          "Grilled chicken",
          "Green beans"
        ]
      },
      {
        "it": [
          "Cous cous alle verdure",
          "Sgombro al forno",
          "Zucchine al forno"
        ],
        "en": [
          "Vegetable couscous",
          "Baked mackerel",
          "Baked zucchini"
        ]
      },
      {
        "it": [
          "Cous cous con verdure",
          "Hummus",
          "Zucchine al forno"
        ],
        "en": [
          "Couscous with vegetables",
          "Hummus",
          "Baked zucchini"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Parmigiana di melanzane",
          "Bresaola con grana",
          "Insalata"
        ],
        "en": [
          "Eggplant parmigiana",
          "Bresaola with grana cheese",
          "Salad"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "seppioline in umido",
          "Spinaci"
        ],
        "en": [
          "Basmati rice",
          "Stewed cuttlefish",
          "Spinach"
        ]
      },
      {
        "it": [
          "Parmigiana di melanzane",
          "frittata con formaggio",
          "Spinaci"
        ],
        "en": [
          "Eggplant parmigiana",
          "Cheese omelette",
          "Spinach"
        ]
      }
    ]
  },
  {
    "date": "2026-07-20",
    "lunch": [
      {
        "it": [
          "Pasta al pomodoro fresco",
          "Arrosto di vitello",
          "Verdure miste"
        ],
        "en": [
          "Pasta with fresh tomato",
          "Roast veal",
          "Mixed vegetables"
        ]
      },
      {
        "it": [
          "Pasta al pesto",
          "Salmone al forno",
          "Patate arrosto"
        ],
        "en": [
          "Pesto pasta",
          "Baked salmon",
          "Roast potatoes"
        ]
      },
      {
        "it": [
          "pasta in crema di peperoni",
          "Falafel al forno",
          "Verdure miste"
        ],
        "en": [
          "Pasta with pepper cream",
          "Baked falafel",
          "Mixed vegetables"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Riso basmati",
          "Pollo al curry",
          "Verdure"
        ],
        "en": [
          "Basmati rice",
          "Chicken curry",
          "Vegetables"
        ]
      },
      {
        "it": [
          "pasta alla crudaiola",
          "Merluzzo al forno",
          "Patate"
        ],
        "en": [
          "Pasta with raw tomato sauce",
          "Baked cod",
          "Potatoes"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "Frittata alle verdure",
          "Verdure"
        ],
        "en": [
          "Basmati rice",
          "Vegetable omelette",
          "Vegetables"
        ]
      }
    ]
  },
  {
    "date": "2026-07-21",
    "lunch": [
      {
        "it": [
          "Pasta al pomodoro",
          "Petto di pollo alla griglia",
          "Zucchine grigliate"
        ],
        "en": [
          "Tomato pasta",
          "Grilled chicken breast",
          "Grilled zucchini"
        ]
      },
      {
        "it": [
          "Pasta alla crema di zucchine",
          "branzino al forno",
          "Carote al vapore"
        ],
        "en": [
          "Pasta with zucchini cream",
          "Baked sea bass",
          "Steamed carrots"
        ]
      },
      {
        "it": [
          "Pasta al pesto",
          "Burger di ceci",
          "Zucchine grigliate"
        ],
        "en": [
          "Pasta with pesto",
          "Chickpea burger",
          "Grilled zucchini"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Lasagna alla bolognese",
          "Roast beef",
          "Insalata mista"
        ],
        "en": [
          "Lasagna Bolognese",
          "Roast beef",
          "Mixed salad"
        ]
      },
      {
        "it": [
          "riso basmati",
          "Salmone al forno",
          "Fagiolini"
        ],
        "en": [
          "Basmati rice",
          "Baked salmon",
          "Green beans"
        ]
      },
      {
        "it": [
          "Lasagna alle verdure",
          "Felafel",
          "Insalata mista"
        ],
        "en": [
          "Vegetable lasagna",
          "Falafel",
          "Mixed salad"
        ]
      }
    ]
  },
  {
    "date": "2026-07-22",
    "lunch": [
      {
        "it": [
          "Pasta alla norma",
          "Tacchino arrosto",
          "Piselli"
        ],
        "en": [
          "Pasta alla Norma",
          "Roast turkey",
          "Peas"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "seppioline al limone",
          "verdure al forno"
        ],
        "en": [
          "Basmati rice",
          "Cuttlefish with lemon",
          "Baked vegetables"
        ]
      },
      {
        "it": [
          "Pasta alla norma",
          "Burger vegetale",
          "Piselli"
        ],
        "en": [
          "Pasta alla Norma",
          "Veggie burger",
          "Peas"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Pasta integrale alle verdure",
          "Hamburger di manzo",
          "Patate al forno"
        ],
        "en": [
          "Wholewheat pasta with vegetables",
          "Beef burger",
          "Baked potatoes"
        ]
      },
      {
        "it": [
          "Gnocchi al pomodoro",
          "Orata al forno",
          "Verdure grigliate"
        ],
        "en": [
          "Gnocchi with tomato sauce",
          "Baked sea bream",
          "Grilled vegetables"
        ]
      },
      {
        "it": [
          "Gnocchi al pomodoro",
          "Tortino di patate e formaggio",
          "Verdure grigliate"
        ],
        "en": [
          "Gnocchi with tomato sauce",
          "Potato and cheese pie",
          "Grilled vegetables"
        ]
      }
    ]
  },
  {
    "date": "2026-07-23",
    "lunch": [
      {
        "it": [
          "Pasta tonno e pomodoro",
          "Lonza al forno",
          "Fagiolini"
        ],
        "en": [
          "Pasta with tuna and tomato",
          "Baked pork loin",
          "Green beans"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "platessa al pomodoro",
          "Carote"
        ],
        "en": [
          "Basmati rice",
          "Plaice with tomato",
          "Carrots"
        ]
      },
      {
        "it": [
          "riso con crema di pomodoro crudo",
          "Polpette di ceci",
          "Carote"
        ],
        "en": [
          "Rice with raw tomato cream",
          "Chickpea patties",
          "Carrots"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Cannelloni ricotta e spinaci",
          "Prosciutto cotto",
          "Insalata"
        ],
        "en": [
          "Ricotta and spinach cannelloni",
          "Cooked ham",
          "Salad"
        ]
      },
      {
        "it": [
          "Riso alle verdure",
          "Platessa al forno",
          "Broccoli"
        ],
        "en": [
          "Rice with vegetables",
          "Baked plaice",
          "Broccoli"
        ]
      },
      {
        "it": [
          "Cannelloni ricotta e spinaci",
          "Arrosto di ceci",
          "Insalata"
        ],
        "en": [
          "Ricotta and spinach cannelloni",
          "Roast chickpeas",
          "Salad"
        ]
      }
    ]
  },
  {
    "date": "2026-07-24",
    "lunch": [
      {
        "it": [
          "Pasta primavera",
          "Pollo alla griglia",
          "Patate lesse"
        ],
        "en": [
          "Pasta primavera",
          "Grilled chicken",
          "Boiled potatoes"
        ]
      },
      {
        "it": [
          "Cous cous alle verdure",
          "Sgombro al forno",
          "Zucchine"
        ],
        "en": [
          "Vegetable couscous",
          "Baked mackerel",
          "Zucchini"
        ]
      },
      {
        "it": [
          "Cous cous con verdure",
          "Arrosto di ceci",
          "Zucchine"
        ],
        "en": [
          "Couscous with vegetables",
          "Roast chickpeas",
          "Zucchini"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "pasta al ragu",
          "Bresaola con grana",
          "Insalata"
        ],
        "en": [
          "Pasta with ragù",
          "Bresaola with grana cheese",
          "Salad"
        ]
      },
      {
        "it": [
          "riso basmati",
          "Tacchino alla griglia",
          "Spinaci"
        ],
        "en": [
          "Basmati rice",
          "Grilled turkey",
          "Spinach"
        ]
      },
      {
        "it": [
          "Parmigiana di melanzane",
          "Insalata ricca( insalata, pom, ceci e feta)",
          "Spinaci"
        ],
        "en": [
          "Eggplant parmigiana",
          "Rich salad (lettuce, tomato, chickpeas and feta)",
          "Spinach"
        ]
      }
    ]
  },
  {
    "date": "2026-07-25",
    "lunch": [
      {
        "it": [
          "Pasta al pomodoro fresco",
          "Arrosto di vitello",
          "Verdure miste"
        ],
        "en": [
          "Pasta with fresh tomato",
          "Roast veal",
          "Mixed vegetables"
        ]
      },
      {
        "it": [
          "Pasta con crema di zucchine",
          "Salmone al forno",
          "Patate arrosto"
        ],
        "en": [
          "Pasta with zucchini cream",
          "Baked salmon",
          "Roast potatoes"
        ]
      },
      {
        "it": [
          "Pasta al pesto",
          "Falafel al forno",
          "Verdure miste"
        ],
        "en": [
          "Pasta with pesto",
          "Baked falafel",
          "Mixed vegetables"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Riso basmati",
          "Pollo alla griglia",
          "Verdure"
        ],
        "en": [
          "Basmati rice",
          "Grilled chicken",
          "Vegetables"
        ]
      },
      {
        "it": [
          "Pasta al tonno",
          "Merluzzo al forno",
          "Patate"
        ],
        "en": [
          "Tuna pasta",
          "Baked cod",
          "Potatoes"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "Frittata alle verdure",
          "Verdure"
        ],
        "en": [
          "Basmati rice",
          "Vegetable omelette",
          "Vegetables"
        ]
      }
    ]
  },
  {
    "date": "2026-07-26",
    "lunch": [
      {
        "it": [
          "Pasta al pomodoro",
          "Petto di pollo alla griglia",
          "Zucchine grigliate"
        ],
        "en": [
          "Tomato pasta",
          "Grilled chicken breast",
          "Grilled zucchini"
        ]
      },
      {
        "it": [
          "Pasta al pesto",
          "Merluzzo al forno",
          "Carote al vapore"
        ],
        "en": [
          "Pasta with pesto",
          "Baked cod",
          "Steamed carrots"
        ]
      },
      {
        "it": [
          "Pasta al pesto e fagiolini",
          "Burger di ceci",
          "Zucchine grigliate"
        ],
        "en": [
          "Pesto pasta with green beans",
          "Chickpea burger",
          "Grilled zucchini"
        ]
      }
    ],
    "dinner": [
      {
        "it": [
          "Lasagna alla bolognese",
          "Roast beef",
          "Insalata mista"
        ],
        "en": [
          "Lasagna Bolognese",
          "Roast beef",
          "Mixed salad"
        ]
      },
      {
        "it": [
          "Riso basmati",
          "Salmone al forno",
          "Fagiolini"
        ],
        "en": [
          "Basmati rice",
          "Baked salmon",
          "Green beans"
        ]
      },
      {
        "it": [
          "Lasagna alle verdure",
          "Arrosto di ceci",
          "Insalata mista"
        ],
        "en": [
          "Vegetable lasagna",
          "Roast chickpeas",
          "Mixed salad"
        ]
      }
    ]
  }
];
